# Generated by Django 2.2.1 on 2021-02-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('author', models.CharField(blank=True, max_length=256, null=True)),
                ('image', models.CharField(blank=True, max_length=256, null=True)),
                ('year', models.PositiveIntegerField(blank=True, default=9, null=True)),
                ('price', models.PositiveIntegerField(blank=True, default=-1.0, null=True)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('bestseller', models.BooleanField(default=False)),
            ],
        ),
    ]
